# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageURL',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
