# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_item', '0007_auto_20170503_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rental',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='add_item.Rental'),
            preserve_default=False,
        ),
    ]
