# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_item', '0008_message_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_request_message',
            field=models.BooleanField(default=False),
        ),
    ]
